export type Lang = "en" | "hi";

export const LANG_COOKIE = "jobsera_lang";

// Static UI-string dictionary. These are translated once, by us, and never
// hit the translation API — so all UI chrome switches instantly with zero
// cost and zero latency, regardless of traffic. Dynamic database content
// (job/blog text) is translated separately via lib/translate.ts.
export const dictionary = {
  en: {
    nav_jobs: "Jobs",
    nav_blogs: "Career Insights",
    nav_about: "About",
    nav_contact: "Contact",
    nav_terms: "Terms & Conditions",
    nav_privacy: "Privacy Policy",
    nav_login: "Login",
    search_placeholder: "Search jobs...",
    apply_now: "Apply Now →",
    salary_heading: "Salary / Pay Scale",
    explore_jobs: "Explore Jobs",
    looking_for_opportunities: "Looking for opportunities?",
    back_to_insights: "← Back to Career Insights",
    back_to_jobs: "← Back to Jobs",
    related_links: "Related Links",
    lang_toggle_label: "हिंदी",

    job_overview: "Job Overview",
    important_dates: "Important Dates",
    application_start_date: "Application Start Date:",
    last_date_label: "Last Date:",
    exam_date_label: "Exam Date:",
    eligibility: "Eligibility",
    educational_qualification: "Educational Qualification:",
    starting_age: "Starting Age:",
    years_suffix: "years",
    age_limit_label: "Age Limit:",
    age_relaxation_label: "Age Relaxation:",
    application_details: "Application Details",
    application_mode_label: "Application Mode:",
    application_fee_label: "Application Fee:",
    selection_process_heading: "Selection Process",
    documents_required_heading: "Documents Required",
    about_opportunity: "About this opportunity",
    official_links: "Official Links",
    view_notification: "View Official Notification →",
    vacancy_singular: "Vacancy",
    vacancy_plural: "Vacancies",
    contact_heading: "Interested in this opportunity?",
    contact_body:
      "Review the recruitment information carefully before applying. For enquiries or application-related information, contact Jobsera using the email address below.",

    // Jobs listing page
    find_next_job: "Find Your Next Job",
    jobs_page_description:
      "Explore the latest job opportunities and find the one that matches your qualification and goals.",
    search_jobs_label: "Search jobs",
    search_jobs_input_placeholder: "Search by job, organization, location...",
    qualification_label: "Qualification",
    clear_filters: "Clear Filters",
    job_singular: "Job",
    job_plural: "Jobs",
    found_suffix: "Found",
    loading_jobs: "Loading jobs...",
    no_jobs_found_heading: "No jobs found",
    no_jobs_found_body: "Try changing your search or qualification filter.",
    view_all_jobs: "View All Jobs",
    previous_label: "← Previous",
    next_label: "Next →",
    view_job_link: "View Job →",
    jobs_cta_heading: "Looking for your next opportunity?",
    jobs_cta_body: "Keep checking Jobsera for the latest opportunities.",
    back_to_home: "Back to Home",

    // Blogs listing page
    learn_prepare_grow: "Learn. Prepare. Grow.",
    blogs_page_description:
      "Practical career information, job search guidance and useful insights to help you make better decisions about your career.",
    explore_career_resources: "Explore Career Resources",
    explore_career_resources_desc:
      "Read useful guides and insights designed to help you prepare for your next opportunity.",
    search_insights_placeholder: "Search career insights...",
    search_button: "Search",
    showing_results_for: "Showing results for",
    no_articles_found_heading: "No articles found.",
    try_different_keyword: "Try searching with a different keyword.",
    no_articles_available_heading: "No articles available yet.",
    new_resources_soon: "New career resources will appear here soon.",
    read_article_link: "Read article →",
    unable_to_load_articles: "Unable to load articles",
    try_again_later: "Please try again later.",
    find_next_opportunity: "Find your next opportunity.",
  },
  hi: {
    nav_jobs: "नौकरियाँ",
    nav_blogs: "करियर जानकारी",
    nav_about: "हमारे बारे में",
    nav_contact: "संपर्क करें",
    nav_terms: "नियम व शर्तें",
    nav_privacy: "गोपनीयता नीति",
    nav_login: "लॉगिन",
    search_placeholder: "नौकरी खोजें...",
    apply_now: "अभी आवेदन करें →",
    salary_heading: "वेतन",
    explore_jobs: "नौकरियाँ देखें",
    looking_for_opportunities: "अवसर की तलाश है?",
    back_to_insights: "← करियर जानकारी पर वापस जाएँ",
    back_to_jobs: "← नौकरियों पर वापस जाएँ",
    related_links: "संबंधित लिंक",
    lang_toggle_label: "English",

    job_overview: "नौकरी का विवरण",
    important_dates: "महत्वपूर्ण तिथियाँ",
    application_start_date: "आवेदन प्रारंभ तिथि:",
    last_date_label: "अंतिम तिथि:",
    exam_date_label: "परीक्षा तिथि:",
    eligibility: "पात्रता",
    educational_qualification: "शैक्षणिक योग्यता:",
    starting_age: "न्यूनतम आयु:",
    years_suffix: "वर्ष",
    age_limit_label: "आयु सीमा:",
    age_relaxation_label: "आयु में छूट:",
    application_details: "आवेदन विवरण",
    application_mode_label: "आवेदन का तरीका:",
    application_fee_label: "आवेदन शुल्क:",
    selection_process_heading: "चयन प्रक्रिया",
    documents_required_heading: "आवश्यक दस्तावेज़",
    about_opportunity: "इस अवसर के बारे में",
    official_links: "आधिकारिक लिंक",
    view_notification: "आधिकारिक सूचना देखें →",
    vacancy_singular: "रिक्ति",
    vacancy_plural: "रिक्तियाँ",
    contact_heading: "इस अवसर में रुचि है?",
    contact_body:
      "आवेदन करने से पहले भर्ती जानकारी को ध्यान से पढ़ें। पूछताछ या आवेदन से जुड़ी जानकारी के लिए नीचे दिए गए ईमेल पते पर Jobsera से संपर्क करें।",

    find_next_job: "अपनी अगली नौकरी खोजें",
    jobs_page_description:
      "नवीनतम नौकरी के अवसर देखें और अपनी योग्यता व लक्ष्यों के अनुसार सही अवसर खोजें।",
    search_jobs_label: "नौकरी खोजें",
    search_jobs_input_placeholder: "नौकरी, संस्था, स्थान से खोजें...",
    qualification_label: "योग्यता",
    clear_filters: "फ़िल्टर हटाएं",
    job_singular: "नौकरी",
    job_plural: "नौकरियाँ",
    found_suffix: "मिलीं",
    loading_jobs: "नौकरियाँ लोड हो रही हैं...",
    no_jobs_found_heading: "कोई नौकरी नहीं मिली",
    no_jobs_found_body: "अपनी खोज या योग्यता फ़िल्टर बदलकर देखें।",
    view_all_jobs: "सभी नौकरियाँ देखें",
    previous_label: "← पिछला",
    next_label: "अगला →",
    view_job_link: "नौकरी देखें →",
    jobs_cta_heading: "अपने अगले अवसर की तलाश है?",
    jobs_cta_body: "नवीनतम अवसरों के लिए Jobsera देखते रहें।",
    back_to_home: "मुखपृष्ठ पर वापस जाएँ",

    learn_prepare_grow: "सीखें। तैयारी करें। आगे बढ़ें।",
    blogs_page_description:
      "आपके करियर से जुड़े बेहतर निर्णय लेने में मदद के लिए व्यावहारिक जानकारी और उपयोगी सुझाव।",
    explore_career_resources: "करियर संसाधन देखें",
    explore_career_resources_desc:
      "अपने अगले अवसर की तैयारी में मदद के लिए उपयोगी गाइड और जानकारी पढ़ें।",
    search_insights_placeholder: "करियर जानकारी खोजें...",
    search_button: "खोजें",
    showing_results_for: "के लिए परिणाम दिखा रहे हैं",
    no_articles_found_heading: "कोई लेख नहीं मिला।",
    try_different_keyword: "किसी अन्य शब्द से खोजने का प्रयास करें।",
    no_articles_available_heading: "अभी तक कोई लेख उपलब्ध नहीं है।",
    new_resources_soon: "नए करियर संसाधन जल्द ही यहाँ दिखेंगे।",
    read_article_link: "लेख पढ़ें →",
    unable_to_load_articles: "लेख लोड नहीं हो सके",
    try_again_later: "कृपया बाद में पुनः प्रयास करें।",
    find_next_opportunity: "अपना अगला अवसर खोजें।",
  },
} as const;

export function t(lang: Lang, key: keyof (typeof dictionary)["en"]): string {
  return dictionary[lang][key];
}

